frictionlessdata/goodtables.io

- .env.example
- .travis.yml
- Makefile
- Procfile
- README.md
- devapp.py
- goodtablesio/app.py
- goodtablesio/config.py
- goodtablesio/helpers/create.py
- requirements.dev
- requirements.in
- requirements.txt
> Implemented CI deployment

- Makefile
- goodtablesio/templates/job.html
- requirements.in
- requirements.txt
> Improved job view

- goodtablesio/app.py
- goodtablesio/blueprints/site.py
- goodtablesio/templates/error404.html
- goodtablesio/templates/error500.html
- goodtablesio/templates/home.html
- goodtablesio/templates/job.html
- goodtablesio/templates/jobs.html
- goodtablesio/tests/blueprints/test_site.py
- fixes #40 
- added error handlers/templates
> Implemented simple jobs UI

- goodtablesio/plugins/github/tasks.py
- fixes #38 
---
@amercader 
I was analyzing code for error handling issue and just realized that we're free to clean our github repo the simplest way because local files is not used but validation task.
> Implemented gihub repo removal

- .env.example
- .travis.yml
- goodtablesio/config.py
- goodtablesio/helpers/create.py
- goodtablesio/helpers/prepare.py
- goodtablesio/models.py
- goodtablesio/plugins/github/blueprint.py
- goodtablesio/plugins/github/tasks.py
- goodtablesio/plugins/github/utils.py
- goodtablesio/services.py
- goodtablesio/tasks.py
- goodtablesio/tests/factories.py
- goodtablesio/tests/helpers/test_create.py
- goodtablesio/tests/helpers/test_prepare.py
- goodtablesio/tests/plugins/github/test_utils.py
Fixes #41 
@roll I need to write some more tests and there is a failure caused by using dataset, but this is ready for review if you want to start having a look.
I've made some changes to the way job configs are prepared, what plugins can store in the DB and what the validation task returns. I recommend to follow the commits as I've separated
> Set GitHub Status

- goodtablesio/plugins/github/tasks.py
- goodtablesio/tests/plugins/github/test_tasks.py
> Fix nested files not found in Github repos

- goodtablesio/helpers/create.py
- goodtablesio/models.py
- goodtablesio/plugins/github/blueprint.py
- goodtablesio/plugins/github/tasks.py
- goodtablesio/tasks.py
- goodtablesio/tests/factories.py
- goodtablesio/tests/test_tasks.py
> Added tasks error handling

- goodtablesio/templates/job.html
There was an error with errors rendering (table per error instead of row per error)
> Fixed job report

- goodtablesio/blueprints/api.py
- fixes #19
---
@amercader 
Is it what we're looking for?
> Add all api errors catching 

- .travis.yml
- Makefile
- README.md
- alembic.ini
- goodtablesio/helpers/create.py
- goodtablesio/plugins/github/tasks.py
- goodtablesio/services.py
- goodtablesio/tasks.py
- migrations/config.py
- migrations/env.py
- migrations/script.py.mako
- migrations/versions/20161207102241_create_jobs_table.py
> Setup migrations

- .travis.yml
- goodtablesio/config.py
- goodtablesio/helpers/__init__.py
- goodtablesio/helpers/prepare.py
- goodtablesio/plugins/github/blueprint.py
- goodtablesio/plugins/github/signals.py
- goodtablesio/plugins/github/tasks.py
- goodtablesio/plugins/github/utils.py
- goodtablesio/tests/helpers/test_prepare.py
- goodtablesio/tests/plugins/github/test_tasks.py
- requirements.in
- requirements.txt
- fixes #39
- improved `validation_conf` creation interface
- improved github plugin modules structure
---
- refs/branches will be addressed in #52 
- limits could be improved with tokens from #69
> Rebased on GitHub API

- goodtablesio/plugins/github/tasks.py
We need to register signals from separate modules importing it.
> Registered github signals

- .travis.yml
- goodtablesio/models/__init__.py
- goodtablesio/models/user.py
- goodtablesio/tests/blueprints/test_api.py
- goodtablesio/tests/blueprints/test_site.py
- goodtablesio/tests/conftest.py
- goodtablesio/tests/factories.py
- goodtablesio/tests/models/test_base.py
- goodtablesio/tests/models/test_job.py
- goodtablesio/tests/models/test_user.py
- goodtablesio/tests/test_factories.py
- goodtablesio/tests/test_tasks.py
- migrations/env.py
- migrations/versions/20161209123518_generate_user_table.py
This is just the SQLAlchemy class and model functions to manage users, plus tests (also some improvements to how test factories work)
> User model

- goodtablesio/plugins/github/blueprint.py
- goodtablesio/plugins/github/signals.py
- goodtablesio/plugins/github/tasks.py
- goodtablesio/tests/plugins/github/test_blueprint.py
- goodtablesio/tests/plugins/github/test_tasks.py
- migrations/env.py
> Added branch/PR support for GitHub plugin

- goodtablesio/blueprints/site.py
- goodtablesio/templates/home.html
- goodtablesio/templates/job.html
- small tweaks to UI of job list and report
> Improved UI of job list and report

- goodtablesio/settings.py
- goodtablesio/tests/utils/test_jobconf.py
- goodtablesio/utils/jobconf.py
- requirements.in
- requirements.txt
> Rebased on tabulator 0.13 to support more formats

- goodtablesio/schemas/job-conf.yml
- goodtablesio/schemas/validation-conf.yml
- goodtablesio/tests/tasks/test_validate.py
- goodtablesio/tests/utils/test_jobconf.py
- requirements.in
- requirements.txt
- fixes #75
- fixed configuration settings parameters naming (camelCase -> snake)
---
> Added skip_rows source param

- goodtablesio/exceptions.py
- goodtablesio/plugins/s3/blueprint.py
- goodtablesio/plugins/s3/exceptions.py
- goodtablesio/plugins/s3/templates/s3_settings.html
- goodtablesio/plugins/s3/utils/__init__.py
- goodtablesio/plugins/s3/utils/lambdaclient.py
- goodtablesio/plugins/s3/utils/s3client.py
- goodtablesio/templates/layout.html
- goodtablesio/tests/plugins/github/test_blueprint.py
- goodtablesio/tests/plugins/s3/test_blueprint.py
- goodtablesio/tests/plugins/s3/utils/test_lambdaclient.py
- goodtablesio/tests/plugins/s3/utils/test_s3client.py
- goodtablesio/tests/plugins/s3/utils/test_utils.py
@roll some more S3 stuff.
This provides a UI, an endpoint and the helpers to hook into the already merged clients. It sets everything up in AWS but still does not store anything on our DB, that's coming next.
> S3 settings UI (add bucket)

- goodtablesio/templates/job.html
- goodtablesio/tests/blueprints/test_site.py
- fixes [partially] #67
---
More proper UI (for errored job), this page tests, scripts relocation etc will be implemented after #92.
Component project - https://github.com/frictionlessdata/goodtables-vue-js
> Rebased on goodtables-vue-js to show reports

- goodtablesio/blueprints/user.py
- goodtablesio/tests/blueprints/test_user.py
- goodtablesio/tests/utils/test_jobconf.py
> Clear session on logout

- .dockerignore
- .travis.yml
- Dockerfile
- Makefile
- Procfile
- README.md
- package.json
- server.py
Cleaned up version of @pwalsh great work on #134
New Dockerfile based on Alpine. 
Makefile as task runner.
> Docker based deployment

- .travis.yml
- Dockerfile
- Makefile
- README.md
- frontend/index.html
- goodtablesio/app.py
- goodtablesio/blueprints/site.py
- goodtablesio/blueprints/user.py
- goodtablesio/integrations/github/blueprint.py
- goodtablesio/integrations/s3/blueprint.py
- goodtablesio/settings.py
- goodtablesio/utils/frontend.py
- package.json
- webpack.config.js
> Improved frontend building workflow

- .eslintrc
- frontend/components/GithubSettings.vue
- frontend/tests/GithubSettings.js
- goodtablesio/integrations/github/blueprint.py
- goodtablesio/tests/integrations/github/test_blueprint.py
- package.json
> Moved GitHub repo activate/deactivate control to frontend

- frontend/components/S3Settings.vue
- frontend/tests/S3Settings.js
- goodtablesio/integrations/s3/blueprint.py
- goodtablesio/integrations/s3/models/bucket.py
- goodtablesio/integrations/s3/utils/__init__.py
- goodtablesio/integrations/s3/utils/bucket.py
- goodtablesio/tests/integrations/s3/test_blueprint.py
- goodtablesio/tests/integrations/s3/utils/test_bucket.py
- pylama.ini
> Moved S3 bucket add/remove control to frontend

- goodtablesio/blueprints/api.py
- goodtablesio/integrations/github/tasks/jobconf.py
- goodtablesio/integrations/s3/tasks/jobconf.py
- goodtablesio/schemas/job-conf.yml
- goodtablesio/schemas/validation-conf.yml
- goodtablesio/tasks/validate.py
- goodtablesio/tests/blueprints/test_api.py
- goodtablesio/tests/integrations/github/test_blueprint.py
- goodtablesio/tests/integrations/s3/tasks/test_jobconf.py
- goodtablesio/tests/tasks/test_validate.py
- goodtablesio/tests/utils/test_jobconf.py
- goodtablesio/utils/jobconf.py
- requirements.in
- requirements.txt
- fixes #17
- improved `goodtables.utils.jobconf` API 
- encapsulated YAML parsing
- sync with `goodtables-py`
- and more minor
- recovered POST /api/job
> Added datapackages support

- goodtablesio/schemas/job-conf.yml
- goodtablesio/tests/utils/test_jobconf.py
- pylama.ini
> Make files/datapackages mutually exclusive

- goodtablesio/blueprints/site.py
- goodtablesio/integrations/github/blueprint.py
- goodtablesio/integrations/s3/blueprint.py
- goodtablesio/utils/frontend.py
@roll an easy one to get started
> Add common props in a single place to avoid duplication

- frontend/components/Dashboard.vue
- frontend/components/Source.vue
- frontend/components/SourceList.vue
- frontend/components/SourceListItem.vue
- frontend/styles/_app_layout.scss
- frontend/styles/_panels.scss
- frontend/tests/Dashboard.js
- goodtablesio/blueprints/site.py
- goodtablesio/integrations/github/models/repo.py
- goodtablesio/integrations/s3/models/bucket.py
- goodtablesio/models/job.py
- goodtablesio/models/source.py
- goodtablesio/tests/blueprints/test_site.py
- goodtablesio/tests/integrations/github/test_blueprint.py
- goodtablesio/tests/integrations/s3/test_blueprint.py
Fixes #104 
Include the last job per source (if any) and sort by the date it was created. Rename all "job" params to "source" to make it more consistent. Handle sources with no jobs.
> Return user's sources on dashboard

- frontend/components/Dashboard.vue
- frontend/components/SourceList.vue
- frontend/components/SourceListItem.vue
- frontend/styles/_app_layout.scss
- frontend/styles/_app_theme.scss
- frontend/styles/_buttons.scss
- goodtablesio/blueprints/site.py
- goodtablesio/models/job.py
- goodtablesio/models/source.py
- package.json
Removed reports, proper ordering of sources, display timestamps
Outstanding design issues in #187
> New Dashboard implementation

- Makefile
- goodtablesio/__init__.py
- goodtablesio/commands.py
- goodtablesio/integrations/github/tasks/repos.py
- goodtablesio/integrations/github/utils/repos.py
- goodtablesio/integrations/s3/blueprint.py
- goodtablesio/integrations/s3/utils/__init__.py
- goodtablesio/integrations/s3/utils/bucket.py
- goodtablesio/settings.py
- goodtablesio/tests/integrations/github/conftest.py
- goodtablesio/tests/integrations/github/tasks/test_repos.py
- goodtablesio/tests/integrations/github/utils/test_repos.py
- goodtablesio/tests/integrations/s3/test_blueprint.py
- goodtablesio/tests/integrations/s3/utils/test_bucket.py
- goodtablesio/tests/test_commands.py
Partially fixes #113 
* Add command for make users admins
* Limit access to private GitHub repos on free plan
* Limit number of S3 buckets on free plan
I need to work on the access checks for viewing the source pages but I'll wait until #190 goes in so the endpoints are finished.
> Various auth / plans features

- goodtablesio/models/integration.py
- goodtablesio/models/source.py
- goodtablesio/tests/integrations/s3/models/test_s3bucket.py
> Fixed s3 remove bucket action

- frontend/components/Error401.vue
- frontend/index.js
- goodtablesio/app.py
- goodtablesio/blueprints/site.py
- goodtablesio/integrations/github/tasks/repos.py
- goodtablesio/models/integration.py
- goodtablesio/models/internal_job.py
- goodtablesio/models/source.py
- goodtablesio/tests/blueprints/test_site.py
- goodtablesio/tests/factories.py
Public repos are open to everyone. Private repos only to paid plan users. S3 buckets only to the owner user.
Added custom 401 page.
> Check source page access

- frontend/components/Home.vue
- frontend/tests/Home.js
- goodtablesio/auth.py
- goodtablesio/blueprints/site.py
- goodtablesio/settings.py
- goodtablesio/tests/blueprints/test_user.py
- goodtablesio/tests/integrations/github/utils/test_status.py
- tests/main.js
> Proper GitHub OAuth scopes

- goodtablesio/integrations/github/blueprint.py
- goodtablesio/integrations/github/utils/hook.py
- goodtablesio/integrations/github/utils/status.py
- goodtablesio/tests/integrations/github/test_blueprint.py
- goodtablesio/tests/integrations/github/utils/test_hook.py
- goodtablesio/tests/integrations/github/utils/test_status.py
Fixes #207 
Fix author link and branch name on reports
> Fix #207 and some tests that were skipped

- goodtablesio/settings.py
- goodtablesio/utils/jobconf.py
- requirements.in
- requirements.txt
- following of https://github.com/frictionlessdata/goodtables-py/issues/189
> Updated goodtables and tabulator versions

- frontend/components/ReportErrorGroup.vue
- frontend/components/ReportTable.vue
- frontend/styles/_report.scss
- frontend/styles/_simple_layout.scss
- fixes #216
- added headers to error group with context body
- fixed rows order (row number was correct just wrongly ordered rows)
- add button `show 10 more rows` when table is truncated
> Minor report improvements

- Makefile
- frontend/components/ReportErrorGroup.vue
- frontend/components/ReportTable.vue
- frontend/spec.json
- frontend/styles/_report.scss
- frontend/tests/ReportErrorGroup.js
- frontend/tests/ReportTable.js
- package.json
- fixes #215 
---
This based on Data Quality Spec update draft - https://github.com/frictionlessdata/data-quality-spec/pull/12
> Improve error descriptions on job reports

- goodtablesio/tests/integrations/github/test_signals.py
@roll These are tests for a critical fix that I pushed directly to master last Friday (6eb4159)
> Tests for #218 (github signals)

- frontend/components/Report.vue
- frontend/tests/fixtures/report.json
- goodtablesio/tasks/base.py
- goodtablesio/tasks/validate.py
- goodtablesio/tests/tasks/test_base.py
- goodtablesio/tests/tasks/test_validate.py
- goodtablesio/tests/utils/test_jobconf.py
- goodtablesio/utils/jobconf.py
- pylama.ini
- requirements.in
- requirements.txt
- fixes #224
- fixes #223
- fixes #214 
- fixes #208
---
Issues #224, #223 and #208 fixed by https://github.com/frictionlessdata/goodtables-py/pull/193 and issue #214 also improved by `goodtables-py` update + added more details about job conf validation errors.
> Improve errored job reports, bug fixes

- goodtablesio/integrations/github/tasks/repos.py
- migrations/versions/20170529131456_make_sources_name_unique.py
> Properly handle updated/deleted github repos

- goodtablesio/integrations/github/tasks/repos.py
- migrations/versions/20170529205734_make_sources_conf_github_id_unique.py
> Properly handle renamed GitHub repos

- frontend/components/ReportTable.vue
- requirements.in
- requirements.txt
> Fixed no headers error

- frontend/components/Settings.vue
- frontend/components/SettingsS3.vue
- frontend/components/SettingsTokens.vue
- goodtablesio/__init__.py
- goodtablesio/blueprints/api.py
- goodtablesio/blueprints/site.py
- goodtablesio/blueprints/user.py
- goodtablesio/models/api_token.py
- goodtablesio/models/base.py
- goodtablesio/models/user.py
- goodtablesio/tests/blueprints/test_api.py
- goodtablesio/tests/models/test_user.py
- goodtablesio/utils/view.py
- migrations/versions/20170606181827_create_api_tokens_table.py
- connects #217 by adding database/model/api/UI support for API tokens
> API tokens support

- goodtablesio/__init__.py
- goodtablesio/blueprints/api.py
- goodtablesio/integrations/api/__init__.py
- goodtablesio/integrations/api/models/api_source.py
- goodtablesio/models/base.py
- goodtablesio/models/job.py
- goodtablesio/models/source.py
- goodtablesio/tests/blueprints/test_api.py
- goodtablesio/utils/backend.py
> Source support in API

- goodtablesio/blueprints/api.py
- goodtablesio/tests/blueprints/test_api.py
- goodtablesio/utils/backend.py
Minor things that I improved while reviewing the API PRs. Commit messages should be self-explanatory.
> Minor api improvements

- goodtablesio/blueprints/site.py
> Moved try.goodtables.io to subdomain

- frontend/components/DemoForm.vue
- frontend/components/Header.vue
- frontend/tests/Header.js
- goodtablesio/utils/frontend.py
- fixes #256 
---
- added examples based on http://goodtables.okfnlabs.org/ experience (I think just placeholders like hinted in #256 could be confusing but links work good - user don't need to click `validate`)
- fixed header links and typo in demo component description
> Demo component improvements

- .eslintrc
- frontend/components/Report.vue
- frontend/components/ReportErrorGroup.vue
- frontend/spec.json
- package.json
- requirements.in
- requirements.txt
- connects #263 
- fixes #261 
---
This includes:
- update to `data-quality-spec@1.0`
- update to `goodtables@1.4` 
- update to `frictionless-data-specs@1.0`
- update to `tableschema/datapackage@1.0`
- UI fix for old report warnings and custom/legacy errors
> Updated to specs-v1

- requirements.in
- requirements.txt
- fixes https://gitter.im/frictionlessdata/chat?at=59f2e071e44c43700a835828
> Updated to goodtables@1.5, tabulator@1.10

- frontend/components/App.vue
- frontend/components/AppBaseLayout.vue
- frontend/index.html
- goodtablesio/integrations/s3/utils/s3client.py
- connects https://github.com/okfn/devops/issues/142
> Added consent manager, privacy policy

- goodtablesio/integrations/github/utils/hook.py
- goodtablesio/tests/integrations/github/utils/test_hook.py
> GitHub hook: use sender login when username is not available
